name: julog
version: 0.1.0
summary: Julog
description: App zur Fuehrung eines Jugendfeuerwehr-Dienstbuches
confinement: strict
base: core22
grade: stable
apps:
  julog:
    command: julog
    extensions: [gnome]
parts:
  julog:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
