name: Flutter CI

on:
  push:
    tags:
      - v**
  workflow_dispatch:
permissions:
  contents: write
env:
  flutterversion: "3.16.x"
jobs:
  build-and-release-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.flutterversion }}
      - name: Install dependencies
        run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
      - name: Install project dependencies
        run: flutter pub get
      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Enable linux build
        run: flutter config --enable-linux-desktop
      - name: Build artifacts
        run: flutter build linux --release
      - name: Create Archive folder
        run: mkdir -p build/linux/x64/release/bundle/github-release
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: "tar"
          filename: github-release/dienstbuch-${{github.ref_name}}-linux.tar.gz
          directory: build/linux/x64/release/bundle
          exclusions: "github-release .git"
      - name: Linux Release
        uses: softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/linux/x64/release/bundle/github-release/dienstbuch-${{github.ref_name}}-linux.tar.gz
          draft: true

  build-and-release-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.flutterversion }}
      - name: Install project dependencies
        run: flutter pub get
      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Enable windows build
        run: flutter config --enable-windows-desktop
      - name: Build artifacts
        run: flutter build windows --release
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: "zip"
          filename: dienstbuch-${{github.ref_name}}-windows.zip
          directory: build/windows/x64/runner/Release
      - name: Windows Release .zip
        uses: softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/windows/x64/runner/Release/dienstbuch-${{github.ref_name}}-windows.zip
          draft: true
      - name: Compile iss to setup.exe
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.4
        with:
          path: windows/innosetup/setup.iss
          options: /O+ /F"dienstbuch-windows-setup"
      - name: Windows Release setup.exe
        uses: softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: windows/innosetup/Output/dienstbuch-windows-setup.exe
          draft: true

  build-and-release-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.flutterversion }}
      - name: Install project dependencies
        run: flutter pub get
      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Enable macOS build
        run: flutter config --enable-macos-desktop
      - name: Build artifacts
        run: flutter build macos --release
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: "zip"
          filename: dienstbuch-${{github.ref_name}}-macos.zip
          directory: build/macos/Build/Products/Release
      - name: macOS Release
        uses: softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/macos/Build/Products/Release/dienstbuch-${{github.ref_name}}-macos.zip
          draft: true
