on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  flutterversion: "3.x"
jobs:
  flutter-status-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.flutterversion }}
      - name: Install project dependencies
        run: flutter pub get
      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Flutter analyze
        run: flutter analyze
